-- *******************************
-- Name: [Naiba Shabanova]
-- ID: [164598229]
-- Date: [01.02.2024]
-- Purpose: DBS211 Lab 02
-- *******************************
-- Q1 SOLUTION --OK
SELECT OFFICECODE, city, state,
country, phone FROM DBS211_OFFICES;

--Q2 SOLUTION --OK
SELECT EMPLOYEENUMBER, firstname, lastname, 
extension FROM DBS211_EMPLOYEES WHERE OFFICECODE = '1' ORDER BY EMPLOYEENUMBER;

--Q3 SOLUTION --OK
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, 
CONTACTLASTNAME, PHONE FROM DBS211_CUSTOMERS WHERE CITY = 'Paris' ORDER BY CUSTOMERNUMBER;

--Q4 SOLUTION --NOOO
--SELECT CUSTOMERNUMBER, CONCAT(CONTACTLASTNAME, ' ', CONTACTFIRSTNAME) AS CONTACNAME, 
--PHONE FROM DBS211_CUSTOMERS WHERE COUNTRY = 'Canada' ORDER BY CUSTOMERNAME;
SELECT 
    CUSTOMERNUMBER, 
    CONCAT(CONTACTLASTNAME, ' ', CONTACTFIRSTNAME) AS CONTACTNAME, 
    PHONE 
FROM 
    DBS211_CUSTOMERS 
WHERE 
    COUNTRY = 'Canada' 
ORDER BY 
    CONCAT(CONTACTLASTNAME, ' ', CONTACTFIRSTNAME);


--Q5 SOLUTION --
SELECT DISTINCT CUSTOMERNUMBER 
FROM DBS211_PAYMENTS ORDER BY CUSTOMERNUMBER;


--Q6 SOLUTION --OK
SELECT CUSTOMERNUMBER, CHECKNUMBER, AMOUNT 
FROM DBS211_PAYMENTS 
WHERE AMOUNT < 1500 OR AMOUNT > 120000 
ORDER BY AMOUNT DESC;

-- Q7 SOLUTION --OK
 SELECT ORDERNUMBER, ORDERDATE, STATUS, CUSTOMERNUMBER
FROM DBS211_ORDERS
WHERE STATUS = 'Cancelled'
ORDER BY ORDERDATE;

-- Q8 SOLUTION --NOOOO

  SELECT 
  PRODUCTCODE, 
  PRODUCTNAME, 
  BUYPRICE, 
  MSRP, 
  (MSRP - BUYPRICE) AS MARKUP, 
  ROUND(100 * ((MSRP - BUYPRICE) / BUYPRICE), 1) AS PERCMARKUP
FROM 
  DBS211_PRODUCTS 
WHERE 
  ROUND(100 * ((MSRP - BUYPRICE) / BUYPRICE), 1) > 140
ORDER BY 
  PERCMARKUP DESC;


-- Q9 SOLUTION --NOO
SELECT 
  PRODUCTCODE, 
  PRODUCTNAME, 
  QUANTITYINSTOCK 
FROM 
  DBS211_PRODUCTS 
WHERE 
  UPPER(PRODUCTNAME) LIKE '%CO%' 
ORDER BY 
  QUANTITYINSTOCK DESC;

-- Q10 SOLUTION --NOO
SELECT 
  CUSTOMERNUMBER, 
  CONTACTFIRSTNAME, 
  CONTACTLASTNAME 
FROM 
  CUSTOMERS 
WHERE 
  UPPER(CONTACTFIRSTNAME) LIKE 'S%' 
  AND UPPER(CONTACTFIRSTNAME) LIKE '%E%' 
ORDER BY 
  CUSTOMERNUMBER;
